token = '220902047:AAEvcj51oZuHAMfHlJ_2qp8HGLzVZLT04M4'
Telegram = require('telegram-bot-api')

api = new Telegram(
  token: token
  updates: enabled: true)

# Question = (attrs) ->
#   @id = attrs.id
#   @name = attrs.name
#   @text = attrs.text
#   @markup = attrs.markup
#
# Request = (attrs) ->
#   current_question_num = 0
#   @chat_id = attrs.chat_id
#   @type = attrs.type
#   @text = attrs.text
#   @questions = attrs.questions
#   @success_message = attrs.success_message
#   @current_question = current_question_func
#   @next = next_func
#
#   current_question_func = () ->
#     @questions[current_question_num]
#
#   next_func = () ->
#     current_question_num += 1

$requests = []

console.log 'bot server started...'

api.on 'message', (message) ->
  if message
    request = null
    chat_id = message.chat.id

    for r in $requests
      request = r if r.chat_id == chat_id

    unless request
      methods.sendMessage chat_id, $initial_question.text, JSON.stringify($initial_question.markup)

    if message.text.downcase == "cancelar"
      methods.remove_request request
      request = null
      return

    if request
      if request.current_question_num == request.questions.length
        methods.sendMessage chat_id, request.success_message + "\n\nPara me chamar novamente basta mandar um Oi que eu volto. ;) \n\nXau! :*", []
        methods.remove_request request
        return

      current_question = request.questions[request.current_question_num]
      current_question.answer = message.text

      if current_question.answer
        methods.sendMessage chat_id, current_question.text, []
        request.current_question_num += 1
        current_question = request.questions[request.current_question_num]


api.on 'inline.callback.query', (msg) ->
  data = msg.data
  for q in $questions
    if q.id == data

      methods.sendMessage msg.from.id, q.text + " Digite OK para confirmar ou CANCELAR para voltar ao inicio.", []
      r = {
        current_question_num: 0
        chat_id: msg.from.id
        text: q.text
        type: data
        questions: q.questions
        success_message: q.success_message
      }
      $requests.push r


methods =
  sendMessage: (chat_id, text, markup, then_func ) ->
    m = api.sendMessage
      chat_id: chat_id
      text: text
      reply_markup: markup
    m.then (message) ->
       then_func(message) if then_func
    m.catch (err) ->
      console.log err
  ,
  remove_request: (request) ->
    $requests.findIndex(x => x.chat_id == request.chat_id)
    index = $requests.indexOf request
    $requests.splice index, 1 if index isnt -1


$initial_question =
  id: 'initial'
  text: 'Olá, tudo bom? Deseja fazer uma solicitação? Escolha um setor para continuar.'
  markup: { inline_keyboard: [
      [ { text: 'Financeiro', callback_data: 'financial' }
        { text: 'Secretaria', callback_data: 'secretary' } ]
      [ { text: 'Coordenação', callback_data: 'coordination' } ]
    ]
  }

$questions = []
$questions.push  {
  id: 'financial'
  name: 'Financeiro'
  text: 'Você selecionou o setor Financeiro.'
  success_message: 'Sua solicitação foi efetuada com sucesso. Em até 72h ela será atendida.'
  markup: []
  questions: [{ text: "Informe seu nome completo: ", answer: null },
              { text: "Descreva sua solicitação... ", answer: null }]
}


$questions.push {
  id: 'secretary'
  name: 'Secretaria'
  text: 'Você selecionou o setor Secretaria.'
  success_message: 'Sua solicitação foi efetuada com sucesso. Em até 72h ela será atendida.'
  markup: []
  questions: [{ text: "Informe seu nome completo: ", answer: "" },
              { text: "Descreva sua solicitação...", answer: "" }]
}

$questions.push {
  id: 'coordination'
  name: 'Coordenação'
  text: 'Você selecionou o setor Coordenação.'
  success_message: 'Sua solicitação foi efetuada com sucesso. Em até 72h ela será atendida.'
  markup: []
  questions: [{ text: "Informe seu nome completo: ", answer: "" },
              { text: "Descreva sua solicitação...", answer: "" }]
}



# ---
# generated by js2coffee 2.2.0
